import type { User, Notification, Post, Comment } from "./dataType";

const notifications: Notification[] = [
  {
    id: 1,
    title: "歡迎加入 論壇樣板！",
    content: "感謝您加入論壇樣板，希望您在這裡能找到有趣的討論。",
  },
  {
    id: 2,
    title: "預計維護公告",
    content: "論壇樣板將於下週四的 10:00 AM 進行系統維護，預計需 2 小時。",
  },
  {
    id: 3,
    title: "新留言通知",
    content: "您的貼文 'React 18 的並發模式值得升級嗎？' 有新留言。",
  },
];

const authors: User[] = [
  {
    id: 2,
    name: "Alice Johnson",
    description: "前端開發者和 React 愛好者。",
  },
  {
    id: 3,
    name: "Bob Smith",
    description: "UI/UX 設計師和 CSS 愛好者。",
  },
  {
    id: 4,
    name: "Charlie Brown",
    description: "網頁效能工程師和 Vite 粉絲。",
  },
  {
    id: 5,
    name: "David Lee",
    description: "全端開發者和 Next.js 專家。",
  },
  {
    id: 6,
    name: "Eve Walker",
    description: "安全研究員和身份驗證專家。",
  },
  {
    id: 7,
    name: "Frank Harris",
    description: "React 開發者和 Zustand 使用者。",
  },
  {
    id: 8,
    name: "Grace Miller",
    description: "UI 設計師和 shadcn/ui 貢獻者。",
  },
  {
    id: 9,
    name: "Henry Wilson",
    description: "React 開發者和 Server Components 倡導者。",
  },
  {
    id: 10,
    name: "Isabella Carter",
    description: "後端開發者和 Supabase 使用者。",
  },
  {
    id: 11,
    name: "Jack Anderson",
    description: "前端開發者和 React Query/SWR 使用者。",
  },
  {
    id: 12,
    name: "Karen Martinez",
    description: "網頁效能專家和優化愛好者。",
  },
  {
    id: 13,
    name: "Liam Rodriguez",
    description: "後端開發者和 Bun 愛好者。",
  },
  {
    id: 14,
    name: "Mia Thompson",
    description: "WebAssembly 愛好者和效能專家。",
  },
  {
    id: 15,
    name: "Noah White",
    description: "前端開發者和技術趨勢追隨者。",
  },
  {
    id: 16,
    name: "Olivia Lewis",
    description: "前端開發者和 Turbopack 使用者。",
  },
];

const user: User = {
  id: 1,
  name: "1ureka",
  description: "",
};

const generateRandomFile = (): File => {
  const randomSize = Math.floor(Math.random() * 1000) + 1000;
  const randomName = Math.random().toString(36).substring(7);
  return new File([new ArrayBuffer(randomSize)], `${randomName}.pdf`, {
    type: "application/pdf",
  });
};

const posts: Post[] = [
  {
    id: 1,
    title: "React 18 的並發模式值得升級嗎？",
    author: "Alice Johnson",
    content: `React 18 帶來了並發模式，這是一個讓 UI 更新更流暢的重要變革。

    並發模式的核心在於讓 React 可以中斷與恢復渲染，這樣在處理大型應用時，不會因為一次性渲染過多內容而導致畫面卡頓。例如，使用 startTransition 來標記較低優先級的更新，React 會在有閒置時間時處理這些更新，而不會影響高優先級的操作，如用戶輸入。這不僅提升了用戶體驗，也讓開發者可以更靈活地管理狀態更新。

    但是，並發模式也有一些限制，例如對於某些非同步操作的處理可能會有問題，需要開發者注意。總的來說，React 18 的並發模式是一個值得升級的特性，尤其是對於需要處理大量數據或複雜動畫的應用來說。`,
    tags: ["React", "並發模式", "效能優化", "前端開發"],
    photos: [
      { name: "test", url: "test" },
      { name: "test", url: "test" },
    ],
    viewCount: 1024,
    likeCount: 250,
    replyCount: 30,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: 2,
    title: "Tailwind CSS vs. MUI：哪個適合你的專案？",
    author: "Bob Smith",
    content: "這篇文章將比較 Tailwind CSS 和 MUI，分析它們的優缺點，幫助你選擇適合的前端 UI 框架。",
    tags: ["CSS", "MUI", "Tailwind", "前端設計"],
    attachments: [generateRandomFile()],
    viewCount: 1987,
    likeCount: 410,
    replyCount: 75,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-07"),
  },
  {
    id: 3,
    title: "Vite 為何比 Webpack 更快？",
    author: "Charlie Brown",
    content:
      "Vite 採用了原生 ES 模組與即時編譯技術，大幅提升開發速度。傳統的 Webpack 需要在開發時先進行整個專案的打包，這可能導致冷啟動時間過長，尤其是專案規模變大時。而 Vite 則透過 ES 模組的 import 方式，僅在瀏覽器需要時載入對應的模組，避免了不必要的打包過程。此外，Vite 內建的 HMR（熱模組替換）機制，使得開發者可以即時看到代碼變更的效果，減少重新整理的時間。這使 Vite 在開發體驗上遠優於 Webpack，特別是對於大型前端專案而言。",
    tags: ["Vite", "Webpack", "效能", "前端工具"],
    viewCount: 2356,
    likeCount: 590,
    replyCount: 88,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: 4,
    title: "Next.js 14 有哪些新特性值得關注？",
    author: "David Lee",
    content: `Next.js 14 帶來了多項重要更新，包括 Server Actions、App Router 以及更優化的效能提升。

    Server Actions 讓開發者可以在伺服器端直接執行處理邏輯，減少 API 請求的成本，而 App Router 則進一步加強了應用的組織結構，使開發更具彈性。

    此外，Next.js 14 在預渲染與快取機制上也有所提升，讓頁面加載速度更快。這些新特性讓 Next.js 成為前端框架中更具吸引力的選擇，特別是對於需要伺服器端渲染的應用而言。`,
    tags: ["Next.js", "SSR", "前端框架", "效能提升"],
    attachments: [generateRandomFile(), generateRandomFile()],
    viewCount: 3120,
    likeCount: 720,
    replyCount: 120,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: 5,
    title: "前端開發中的 JWT 與 Session 安全性探討",
    author: "Eve Walker",
    content: "JWT 與 Session 各有優缺點，如何確保應用程式的安全性？",
    tags: ["JWT", "Session", "身份驗證", "安全性"],
    viewCount: 1780,
    likeCount: 460,
    replyCount: 95,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: 6,
    title: "如何使用 Zustand 管理 React 狀態？",
    author: "Frank Harris",
    content: "Zustand 是一個輕量級的狀態管理工具，比 Redux 更簡單，適合小型專案。",
    tags: ["React", "Zustand", "狀態管理", "前端開發"],
    photos: [{ name: "test", url: "test" }],
    attachments: [generateRandomFile(), generateRandomFile(), generateRandomFile()],
    viewCount: 1250,
    likeCount: 310,
    replyCount: 60,
    createdAt: new Date("2024-03-25"),
    updatedAt: new Date("2024-03-27"),
  },
  {
    id: 7,
    title: "為什麼你應該考慮使用 shadcn/ui？",
    author: "Grace Miller",
    content: "shadcn/ui 提供了可擴展的 UI 元件，適合喜歡 Tailwind CSS 的開發者。",
    tags: ["shadcn/ui", "Tailwind", "React", "UI 元件"],
    viewCount: 890,
    likeCount: 190,
    replyCount: 45,
    createdAt: new Date("2024-03-30"),
    updatedAt: new Date("2024-04-01"),
  },
  {
    id: 8,
    title: "Server Components 是未來嗎？",
    author: "Henry Wilson",
    content: `React Server Components（RSC）是 React 的一項重要新技術，它允許部分組件在伺服器端渲染，並將結果傳遞給前端。這種方式可以顯著減少瀏覽器端的 JavaScript 負擔，提升效能並減少加載時間。
    例如，某些不需要用戶互動的組件可以完全由伺服器處理，避免前端處理不必要的渲染。
    雖然目前 RSC 仍然在發展中，但它提供了一種全新的開發模式，未來可能會成為大型應用的標準解決方案。`,
    tags: ["React", "Server Components", "SSR", "效能優化"],
    attachments: Array.from({ length: 6 }, generateRandomFile),
    viewCount: 2600,
    likeCount: 680,
    replyCount: 110,
    createdAt: new Date("2024-04-02"),
    updatedAt: new Date("2024-04-05"),
  },
  {
    id: 9,
    title: "如何使用 Supabase 建立完整的後端？",
    author: "Isabella Carter",
    content: `Supabase 是一個開源的 Firebase 替代方案，提供即時資料庫、身份驗證與存儲功能。

    使用 Supabase，可以快速建立一個完整的後端，無需自行管理伺服器。例如，透過 Supabase 的 Postgres 資料庫，可以輕鬆建立關聯式數據表，並使用 RLS（Row-Level Security）確保數據安全。此外，Supabase 內建的 WebSocket 支援讓前端能夠即時監聽資料變更，實現即時更新的功能。對於希望減少後端開發成本的前端工程師來說，Supabase 是一個非常理想的選擇。`,
    tags: ["Supabase", "後端", "資料庫", "身份驗證"],
    viewCount: 1450,
    likeCount: 350,
    replyCount: 65,
    createdAt: new Date("2024-04-07"),
    updatedAt: new Date("2024-04-07"),
  },
  {
    id: 10,
    title: "React Query vs. SWR：哪個資料請求庫更好？",
    author: "Jack Anderson",
    content: "React Query 和 SWR 都是處理 API 資料請求的強大工具，各有優勢。",
    tags: ["React", "React Query", "SWR", "API 處理"],
    photos: [
      { name: "test", url: "test" },
      { name: "test", url: "test" },
    ],
    viewCount: 1875,
    likeCount: 500,
    replyCount: 85,
    createdAt: new Date("2024-04-12"),
    updatedAt: new Date("2024-04-15"),
  },
  {
    id: 11,
    title: "如何讓你的 Web 應用跑得更快？",
    author: "Karen Martinez",
    content: "透過代碼分割、預載資源和使用 CDN，可以讓 Web 應用加速。",
    tags: ["效能優化", "Web 開發", "CDN", "前端最佳化"],
    photos: [
      { name: "test", url: "test" },
      { name: "test", url: "test" },
      { name: "test", url: "test" },
    ],
    viewCount: 2240,
    likeCount: 610,
    replyCount: 130,
    createdAt: new Date("2024-04-18"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: 12,
    title: "為什麼 Bun 可能會取代 Node.js？",
    author: "Liam Rodriguez",
    content: "Bun 具備更快的運行速度、更好的原生支援，成為 Node.js 的強勁對手。",
    tags: ["Bun", "Node.js", "JavaScript", "後端開發"],
    viewCount: 2025,
    likeCount: 490,
    replyCount: 95,
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-04-28"),
  },
  {
    id: 13,
    title: "WebAssembly (WASM) 能提升前端效能嗎？",
    author: "Mia Thompson",
    content: "WASM 可以執行高效能程式碼，讓 Web 應用運行更快。",
    tags: ["WASM", "效能", "Web 開發", "JavaScript"],
    viewCount: 1350,
    likeCount: 290,
    replyCount: 50,
    createdAt: new Date("2024-04-28"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: 14,
    title: "2025 年前端趨勢：你應該學哪些技術？",
    author: "Noah White",
    content: "探索 2025 年最值得學習的前端技術，包括 React Server Components、Edge Functions 等。",
    tags: ["前端趨勢", "新技術", "Web 開發", "React"],
    photos: Array.from({ length: 10 }, (_, i) => ({ name: `test${i}`, url: "test" })),
    attachments: [generateRandomFile(), generateRandomFile(), generateRandomFile()],
    viewCount: 3105,
    likeCount: 840,
    replyCount: 170,
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-03"),
  },
  {
    id: 15,
    title: "如何使用 Turbopack 加速你的前端專案？",
    author: "Olivia Lewis",
    content: "Turbopack 作為 Webpack 的接班人，能讓前端開發更快速。",
    tags: ["Turbopack", "Webpack", "前端工具", "效能提升"],
    attachments: [generateRandomFile(), generateRandomFile()],
    viewCount: 1640,
    likeCount: 420,
    replyCount: 78,
    createdAt: new Date("2024-05-05"),
    updatedAt: new Date("2024-05-05"),
  },
];

//TODO: 製作 comments 假資料，完成後 Post 不會再有 replyCount 欄位
const comments: Comment[] = [
  // 主留言
  {
    id: 1,
    postId: 1,
    userId: 4,
    content: "非常同意作者的觀點，並發模式確實解決了很多效能問題，特別是在處理大量資料的應用程式中。",
    createdAt: new Date("2024-03-01T10:15:00"),
    updatedAt: new Date("2024-03-01T10:15:00"),
  },
  {
    id: 2,
    postId: 1,
    userId: 7,
    content: "我最近在一個專案中實作了 startTransition，確實讓用戶體驗提升不少，尤其是在資料載入時的反應速度。",
    createdAt: new Date("2024-03-01T11:30:00"),
    updatedAt: new Date("2024-03-01T11:30:00"),
  },
  {
    id: 3,
    postId: 1,
    userId: 10,
    content: "雖然並發模式很好，但升級時需要注意某些第三方庫的相容性問題，我遇到過一些 UI 庫不相容的情況。",
    createdAt: new Date("2024-03-01T13:45:00"),
    updatedAt: new Date("2024-03-01T13:45:00"),
  },
  {
    id: 4,
    postId: 1,
    userId: 3,
    content: "有人可以分享一下實際使用 useTransition 的經驗嗎？我還在考慮是否要在專案中導入。",
    createdAt: new Date("2024-03-01T15:20:00"),
    updatedAt: new Date("2024-03-01T15:20:00"),
  },
  {
    id: 5,
    postId: 1,
    userId: 9,
    content: "除了並發模式，React 18 的自動批次處理(Automatic Batching)也是一個很棒的功能，可以減少渲染次數。",
    createdAt: new Date("2024-03-01T16:10:00"),
    updatedAt: new Date("2024-03-01T16:10:00"),
  },
  {
    id: 6,
    postId: 1,
    userId: 12,
    content: "我覺得作者低估了並發模式的學習曲線，對於小型團隊來說可能不值得為此升級。",
    createdAt: new Date("2024-03-01T17:30:00"),
    updatedAt: new Date("2024-03-01T17:30:00"),
  },
  {
    id: 7,
    postId: 1,
    userId: 5,
    content: "想請問一下，有沒有推薦的教學資源來學習這些新功能？官方文件有點太技術性了。",
    createdAt: new Date("2024-03-01T19:05:00"),
    updatedAt: new Date("2024-03-01T19:05:00"),
  },
  {
    id: 8,
    postId: 1,
    userId: 14,
    content: "效能優化不應該只依賴框架的新功能，良好的代碼結構和懂得使用 useMemo/useCallback 同樣重要。",
    createdAt: new Date("2024-03-01T20:40:00"),
    updatedAt: new Date("2024-03-01T20:40:00"),
  },

  // 回覆留言
  {
    id: 9,
    postId: 1,
    parentid: 3,
    userId: 6,
    content: "我也遇到過這個問題！特別是一些動畫庫，有時會有奇怪的行為。你遇到問題的是哪個庫？",
    createdAt: new Date("2024-03-01T14:15:00"),
    updatedAt: new Date("2024-03-01T14:15:00"),
  },
  {
    id: 10,
    postId: 1,
    parentid: 9,
    userId: 10,
    content: "主要是 react-spring 和一些比較老的 UI 庫，需要做不少調整才能正常運作。",
    createdAt: new Date("2024-03-01T14:30:00"),
    updatedAt: new Date("2024-03-01T14:30:00"),
  },
  {
    id: 11,
    postId: 1,
    parentid: 4,
    userId: 7,
    content: "我們在一個有大量表格資料的應用中使用了 useTransition，當用戶篩選資料時體驗好很多，界面不會卡頓。",
    createdAt: new Date("2024-03-01T15:45:00"),
    updatedAt: new Date("2024-03-01T15:45:00"),
  },
  {
    id: 12,
    postId: 1,
    parentid: 11,
    userId: 3,
    content: "感謝分享！這正是我們專案中遇到的情況，看來值得一試。",
    createdAt: new Date("2024-03-01T16:00:00"),
    updatedAt: new Date("2024-03-01T16:00:00"),
  },
  {
    id: 13,
    postId: 1,
    parentid: 7,
    userId: 8,
    content: "我推薦 'React Working Group' 的 YouTube 頻道，他們有很多關於 React 18 新功能的實用教學。",
    createdAt: new Date("2024-03-01T19:20:00"),
    updatedAt: new Date("2024-03-01T19:20:00"),
  },
  {
    id: 14,
    postId: 1,
    parentid: 7,
    userId: 11,
    content: "Josh Comeau 的部落格也有一些很好的文章介紹並發模式，解釋得很清楚。",
    createdAt: new Date("2024-03-01T19:40:00"),
    updatedAt: new Date("2024-03-01T19:40:00"),
  },
  {
    id: 15,
    postId: 1,
    parentid: 6,
    userId: 2,
    content: "我不完全同意。雖然有學習曲線，但即使是小團隊也能從並發模式中獲益，特別是處理表單輸入時。",
    createdAt: new Date("2024-03-01T18:00:00"),
    updatedAt: new Date("2024-03-01T18:00:00"),
  },
  {
    id: 16,
    postId: 1,
    userId: 13,
    content: "有人測試過並發模式在移動設備上的效能差異嗎？我很好奇在低端手機上的表現如何。",
    createdAt: new Date("2024-03-01T21:15:00"),
    updatedAt: new Date("2024-03-01T21:15:00"),
  },
  {
    id: 17,
    postId: 1,
    parentid: 16,
    userId: 15,
    content: "我們有在各種Android設備上測試過，在低端設備上效果更明顯，因為並發模式能更好地管理有限的計算資源。",
    createdAt: new Date("2024-03-01T21:35:00"),
    updatedAt: new Date("2024-03-01T21:35:00"),
  },
  {
    id: 18,
    postId: 1,
    parentid: 8,
    userId: 14,
    content: "補充一點，React 18的並發模式和良好的代碼結構結合起來使用，效果會更好。兩者不是互斥的關係。",
    createdAt: new Date("2024-03-01T22:10:00"),
    updatedAt: new Date("2024-03-01T22:10:00"),
  },
];

export { notifications, authors, user, posts, comments };
